# Config for Rubocop, based on Rubocop v1.50.2.
#
# https://github.com/rubocop/rubocop/blob/v1.50.2/config/default.yml
# https://docs.rubocop.org/rubocop/1.50/cops_security.html

Security/CompoundHash:
  Enabled: true

Security/Eval:
  Enabled: true

Security/IoMethods:
  Enabled: true

Security/JSONLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/Open:
  Enabled: true

Security/YAMLLoad:
  Enabled: true
